### ISSUE TITLE
How to get the model of kaggle.

### ISSUE THREAD

**Issue by li-chx** [khornlund/severstal-steel-defect-detection#9]
I want to perform inference on actual steel to find defects. However, the README does not mention how to use the trained models. I found Kaggle submission records, but the models used in the notebooks seem to be unavailable. There are a total of seven models: 
```
classification:
    b5-1019_084415:
    b5-1019_190940:
segmentation:
    unet-se_resnext50_32x4d-1017_210727-LB-0.91489:
    unet-b5-1016_202517-LB-0.91515:
    fpn-b5-1016_221333-LB-0.91528:
    fpn-b5-1016_203538-LB-0.91393:
    fpn-se_resnext50_32x4d-1018_082516-LB-0.91656: 
```
I would like to know if you still have these models? If not, please tell me how to train them. I plan to train the five segmentation models using the existing configuration files under the experiments directory. However, how should I obtain the two classification models? Should I use the training information in the classification branch? Looking forward to your reply.
